CLIENTS:
  raw:
    file: clients.xlsx
    col: "机构全称"
  extracted:
    file: clients.csv
    col: "机构简称"

TARGETS:
  raw:
    file: targets.xlsx
    col: "机构全称"
  extracted:
    file: targets.csv
    col: "机构简称"

EXTRACTOR:
  user_dicts: [add_prefix.txt,
               corp_suffix.txt]

MATCHER:
  weights:
    phonetic: 0.3
    stroke: 0.35
    radical: 0.35
  ngram: 3
  threshold: 0.6
  topn: 3
